### PR TITLE
Fix missing vector dialect registration from LinalgFuse driver.

### PR DESCRIPTION
**Pull request by MaheshRavishankar**
Also add some unit tests for the single tiling expert driver and
linalg fuse driver.

### CODE REVIEW

**Review by gysit — APPROVED** [review]
nice! need to add these to the test script somehow...

**Comment by MaheshRavishankar** [comment]
That'd be great. Any idea how to do that?

**Comment by gysit** [comment]
> That'd be great. Any idea how to do that?

I will give it a try. There is probably a right way to do it or I can just call lit from python :)

**Comment by MaheshRavishankar** [comment]
IREE has some cmake macro for the tests, but might be too involved for simple testing of this sort

**Comment by gysit** [comment]
yes, I think it would be better to include it in the run_tests.py which is already run by a github action. Although cmake may also be a good option.

**Comment by MaheshRavishankar** [comment]
> yes, I think it would be better to include it in the run_tests.py which is already run by a github action. Although cmake may also be a good option.

If we could get lit testing working with python that would be great too. The command line is pretty simple, last I looked at it seemed very complicated to do internally. Maybe we can sidestep all of that in OSS. If you add this to `run_test.py`. I can figure out how to add it for python

**Pull request merged**
