### PR TITLE
[DoNotCommit] Repro lack of pipelining

### PR DESCRIPTION
**Pull request by nicolasvasilache**
The following command is expected to dump some pipelined IR but it does not:
```
python -m python.examples.matmul.test
```

### CODE REVIEW

**Comment by nicolasvasilache** [comment]
FYI @ThomasRaoux , this repro does not pipeline.
There are other cases that also don't pipeline (e.g. if you remove the interchange vector in the strategy and the vector is hoisted into an iter_args; then I'd try to pipeline the 2nd enclosing loop for instance).

**Comment by ThomasRaoux** [comment]
Summarizing what I wrote on discord:
-There is a recurrence in the loop containing read_ + contract + write so we cannot pipeline
-Technically there is no "real" dependency across iterations however it would require some special handling and this would make the tensor liverange overlap across iteration.

Do we want to handle this kind of case?

**Comment by ThomasRaoux** [comment]
Pushed the new example with bigger II and no interchange.
(the small II was causing the number of stages to be greater than number of iterations)

**Comment by nicolasvasilache** [comment]
works for me, thanks!

**Pull request closed without merging**
