### PR TITLE
Adding a missing dependency (it was removed in 2d7c7cb)

### PR DESCRIPTION
**Pull request by giuseros**
This will solve issue https://github.com/google/iree-llvm-sandbox/issues/43

### CODE REVIEW

**Comment by nicolasvasilache** [comment]
CLA seems to be missing?

**Review by nicolasvasilache — APPROVED** [review]
LGTM.

Good to merge once the CLA is green.

**Comment by giuseros** [comment]
Usual issue with personal/work mail. Basically the mail associated with the CLA is not the mail of my personal github account and this makes github complaining. In theory I fixed that now, but pushing again didn't sort out the issue.

**Comment by nicolasvasilache** [comment]
I reran manually but it is still unhappy ..

**Comment by giuseros** [comment]
I will try to close this pull request and do everything from scratch (refork, resubmit, etc..). Sorry about this

**Pull request closed without merging**
