### PR TITLE
Bump llvm

### PR DESCRIPTION
**Pull request by chelini**

### CODE REVIEW

**Comment by chelini** [comment]
Dear All, unrelated to this I also have a question regarding `createLinalgTransformInterpreterPass`. Why the pass is not exposed to the users? I have a use case where I would like to create the pass and add it to the pass manager. Do you feel it is a good idea to expose the pass?

**Comment by gysit** [comment]
> Dear All, unrelated to this I have a question regarding `createLinalgTransformInterpreterPass`. Why the pass is not exposed to the users? I have a use case where I would like to create the pass and add it to the pass manager. Do you feel it is a good idea to expose the pass?

Others may correct me if I am wrong. I assume there was no use case so far and it is fine exposing the method in the header.

**Comment by chelini** [comment]
> > Dear All, unrelated to this I have a question regarding `createLinalgTransformInterpreterPass`. Why the pass is not exposed to the users? I have a use case where I would like to create the pass and add it to the pass manager. Do you feel it is a good idea to expose the pass?
> 
> Others may correct me if I am wrong. I assume there was no use case so far and it is fine exposing the method in the header.

Thanks.

**Review by gysit — APPROVED** [review]
Thanks!

**Review by nicolasvasilache — CHANGES_REQUESTED** [review]
Can we please split this up in multiple PRs? 

There seem to be multiple unrelated changes all inside a single PR atm.

**Comment by chelini** [comment]
Ok, I will close this, and create multiple smaller PRs.

**Pull request closed without merging**
