### PR TITLE
Iterators: Configure lit for compiler tests and unittests

### PR DESCRIPTION
**Pull request by ingomueller-net**
Not 100% if this follows best practices; this is really just some copy'n'paste + trial'n'error from existing folders...

### CODE REVIEW

**Comment by ingomueller-net** [comment]
This is meant to be merged after #323.

**Comment by ingomueller-net** [comment]
My first attempt made the tests fail. The reason is that, if I change `run_tests.py`, I need to make everything in CI work, which means I need to build the `iterators` subproject. I just added another commit that does that; now the tests pass. What is a bit suspicious is that I don't see the `IteratorsTests` target being built, nor do I see the output of the lit tests, so I am not 100% sure if things are actually run...

**Review by nicolasvasilache — APPROVED** [review]
Looks good assuming the tests go back to green after rebase.

**Comment by ingomueller-net** [comment]
I did small changes since your review: (1) make running the iterator tests in `run_tests.py` optional (because building it is optional), and (2) add a new commit that follows the renaming of `-convert-std-to-llvm` to `-convert-func-to-llvm`.

@nicolasvasilache: You want to check again or should I go ahead and merge?

**Comment by nicolasvasilache** [comment]
`@nicolasvasilache: You want to check again or should I go ahead and merge?`

I guess you have your answer :) thanks!

**Pull request merged**
