### PR TITLE
Move expert definition to C++ passes

### PR DESCRIPTION
**Pull request by MaheshRavishankar**
Turn the python expert into a thin wrapper around the C++ expert

### CODE REVIEW

**Comment by MaheshRavishankar** [comment]
Only the last two commits are part of this PR. The first commit is part of #25

**Review by nicolasvasilache — APPROVED** [review]
Please add a more descriptive comment in line with what we discussed offline: 

```
Move expert definition to C++ passes 
Turn the python expert into a thin wrapper around the C++ expert
```

LGTM but this seems to break the build, please fix before landing.

**Comment by MaheshRavishankar** [comment]
> Please add a more descriptive comment in line with what we discussed offline: 
> 
> ```
> Move expert definition to C++ passes 
> Turn the python expert into a thin wrapper around the C++ expert
> ```
> 
> LGTM but this seems to break the build, please fix before landing. 

The breakage is because CI needs to use a different LLVM commit

**Comment by nicolasvasilache** [comment]
ah yes, I forgot the build automatically pulls down IREE's pinned LLVM version.
Ok if you've tested let's merge then.

**Pull request merged**
